# Generated by Django 5.2.4 on 2025-07-31 20:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=3, unique=True)),
                ('continent', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Pays',
                'verbose_name_plural': 'Pays',
            },
        ),
        migrations.CreateModel(
            name='Bourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('niveau', models.CharField(choices=[('licence', 'Licence'), ('master', 'Master'), ('doctorat', 'Doctorat'), ('master_doctorat', 'Master/Doctorat'), ('licence_master_doctorat', 'Licence/Master/Doctorat'), ('postdoc', 'Post-doctorat')], max_length=30)),
                ('type_bourse', models.CharField(choices=[('complete', 'Complète'), ('partielle', 'Partielle'), ('logement', 'Logement'), ('transport', 'Transport')], max_length=20)),
                ('montant', models.CharField(max_length=100)),
                ('deadline', models.DateTimeField()),
                ('duree', models.CharField(max_length=50)),
                ('domaines_texte', models.TextField(blank=True)),
                ('prerequis', models.TextField()),
                ('organisme', models.CharField(max_length=200)),
                ('nombre_places', models.PositiveIntegerField()),
                ('age_minimum', models.PositiveIntegerField(blank=True, null=True)),
                ('age_maximum', models.PositiveIntegerField(blank=True, null=True)),
                ('moyenne_requise', models.CharField(blank=True, max_length=50)),
                ('test_langue_requis', models.CharField(blank=True, max_length=100)),
                ('avantages_supplementaires', models.TextField(blank=True)),
                ('documents_requis', models.TextField(blank=True)),
                ('lien_candidature', models.URLField(blank=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('actif', models.BooleanField(default=True)),
                ('domaines_etudes', models.ManyToManyField(blank=True, to='core.categorie')),
                ('pays_destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bourses.pays')),
            ],
            options={
                'verbose_name': 'Bourse',
                'verbose_name_plural': 'Bourses',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='CandidatureBourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('en_preparation', 'En préparation'), ('soumise', 'Soumise'), ('en_attente', 'En attente'), ('acceptee', 'Acceptée'), ('refusee', 'Refusée')], default='en_preparation', max_length=20)),
                ('date_candidature', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('notes_personnelles', models.TextField(blank=True)),
                ('bourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatures', to='bourses.bourse')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Candidature de bourse',
                'verbose_name_plural': 'Candidatures de bourses',
                'ordering': ['-date_candidature'],
                'unique_together': {('bourse', 'utilisateur')},
            },
        ),
    ]
