# Generated by Django 5.2.4 on 2025-07-31 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('niveau', models.CharField(choices=[('college', 'Collège'), ('lycee', 'Lycée'), ('superieur', 'Supérieur'), ('professionnel', 'Professionnel')], max_length=20)),
                ('deadline', models.DateTimeField()),
                ('localisation', models.CharField(max_length=100)),
                ('nombre_places', models.CharField(max_length=50)),
                ('prerequis', models.TextField()),
                ('statut', models.CharField(choices=[('ouvert', 'Ouvert'), ('ferme', 'Fermé'), ('en_cours', 'En cours'), ('termine', 'Terminé')], default='ouvert', max_length=20)),
                ('organisme', models.CharField(blank=True, max_length=200)),
                ('frais_inscription', models.CharField(blank=True, max_length=100)),
                ('documents_requis', models.TextField(blank=True)),
                ('lien_inscription', models.URLField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('actif', models.BooleanField(default=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categorie')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.region')),
            ],
            options={
                'verbose_name': 'Concours',
                'verbose_name_plural': 'Concours',
                'ordering': ['-date_creation'],
            },
        ),
    ]
