# Generated by Django 5.2.4 on 2025-07-31 20:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('type_formation', models.CharField(choices=[('en_ligne', 'En ligne'), ('presentiel', 'Présentiel'), ('hybride', 'Hybride')], max_length=20)),
                ('prix', models.CharField(choices=[('gratuite', 'Gratuite'), ('payante', 'Payante')], max_length=20)),
                ('prix_montant', models.CharField(blank=True, max_length=100)),
                ('duree', models.CharField(max_length=50)),
                ('niveau', models.CharField(choices=[('debutant', 'Débutant'), ('intermediaire', 'Intermédiaire'), ('avance', 'Avancé'), ('tous_niveaux', 'Tous niveaux')], max_length=20)),
                ('date_debut', models.DateField()),
                ('localisation', models.CharField(max_length=100)),
                ('organisme', models.CharField(max_length=200)),
                ('note_moyenne', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('nombre_etudiants', models.PositiveIntegerField(default=0)),
                ('certificat_disponible', models.BooleanField(default=False)),
                ('prerequis', models.TextField(blank=True)),
                ('programme', models.TextField(blank=True)),
                ('objectifs', models.TextField(blank=True)),
                ('lien_inscription', models.URLField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('actif', models.BooleanField(default=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categorie')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.region')),
            ],
            options={
                'verbose_name': 'Formation',
                'verbose_name_plural': 'Formations',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='AvisFormation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('commentaire', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis', to='formations.formation')),
            ],
            options={
                'verbose_name': 'Avis de formation',
                'verbose_name_plural': 'Avis de formations',
                'ordering': ['-date_creation'],
                'unique_together': {('formation', 'utilisateur')},
            },
        ),
    ]
